### ISSUE TITLE
Gamescope can't be activated.

### ISSUE THREAD

**Issue by gbj1viciado** [flathub/com.usebottles.bottles#306] opened 2022-01-28 16:31 UTC
I can't activate gamescope even though is already installed as a flatpak.

**Comment by mirkobrombin** [comment] 2022-01-28 17:25
Probably because Bottles is not able to reach gamescope path (?)

**Comment by gbj1viciado** [comment] 2022-01-29 01:36
Well i couldn't  get bottles to use gamescope, on the flatpak version, and on the binary version it just refuses to open any exe with it enabled anyway. I think is something to do with the new version off gamescope. Well i just opened the bottles flatpak using gamescope "gamescope -w 1920 -h 1080  -f -n flatpak run com.usebottles.bottles" that's a good enough fix for me.

**Comment by t-m-w** [comment] 2022-02-06 16:50
Not sure if I should open a new issue, but this issue already describes the problem, despite being closed.

I receive "This feature is not available on your system" when hovering over the Gamescope toggle using the Flatpak. I have gamescope installed as a flatpak as well.

The [release notes for 2022.1.14](https://usebottles.com/blog/release-2022.1.14/#gamescope) indicate that Flatpak support for Gamescope was under consideration. Is this still true?
> This release has initial support for gamescope, the micro-compositor formerly known as steamcompmgr. We made some tests and it seems to work fine but doesn’t came with the Flatpak right now. We could do an update in the next few days to bring it to the Flatpak, perhaps as an extension since not everyone may need this tool.

**Comment by mirkobrombin** [comment] 2022-02-06 17:06
Hi we want to provide it on flatpak too but not scheduled 👀

**Comment by BigmenPixel0** [comment] 2022-02-09 11:15
I [tried](https://github.com/BigmenPixel0/com.usebottles.bottles/commit/770cb760799e9b9618dad031e6dcad082427b336) to add gamescope support, but I don't understand if it works or not. If you run gamescope in the sandbox, then it is displayed in processes, and if you enable it in Bottles, then there is no gamescope process.

**Comment by mirkobrombin** [comment] 2022-02-09 15:21
I'll do a test soon

**Comment by mirkobrombin** [comment] 2022-02-09 15:29
Ok it works but I've found a regression. I'll fix it in 2022.2.14, thanks for your contribution.

**Comment by mirkobrombin** [comment] 2022-02-09 16:06
Fixed by https://github.com/bottlesdevs/Bottles/commit/e2c55b8328f609a2dd2cf13eb1d9b9add47f7b6e

**Closed by mirkobrombin** 2022-02-09 16:06 UTC

**Comment by BigmenPixel0** [comment] 2022-02-09 16:17
> Fixed by [bottlesdevs/Bottles@e2c55b8](https://github.com/bottlesdevs/Bottles/commit/e2c55b8328f609a2dd2cf13eb1d9b9add47f7b6e)

Compiled flatpak with this commit and my patch - it works. So open pr?

**Comment by mirkobrombin** [comment] 2022-02-09 16:22
Already merged, thanks

**Comment by mirkobrombin** [comment] 2022-02-09 16:44
> > Already merged, thanks
> 
> Now I see it, great! :)

Thanks again.
